### ISSUE TITLE
upload_media() should allow the caller to specify media type

### ISSUE THREAD

**Issue by mewio** [odrling/peony-twitter#11]
The upload_media() method always calls get_image_metadata(), which fails on file-like objects if the `magic` package is not installed. This is rather silly, because:

* AFAICT, very common cases like images below photo_size_limit do not use the chunked upload method, and therefore do not require the media type to be specified. In other words, the failing code path is trying to get data that is often completely unnecessary.
* In cases where the media type must be known, the caller could simply tell upload_media() what type of content it is passing, if only upload_media() offered a way to do so. Allowing for this would avoid forcing applications to adopt a dependency on the `magic` package.

I discovered this when I found an application resorting to monkey patching peony's get_image_metadata() in order to specify an `image/png` media type without depending on `magic`... so peony wouldn't complain about being unable to determine the type... which it just throws away anyway.

**Comment by odrling** [comment]
Alright, I'll remove that `get_image_metadata()` call in `upload_media()` and let `_chunked_upload()` find with the media type and media category and add the `media_type` and `media_category` parameters to `upload_media()`.

Also, is there any problem with `magic` that I should be aware of? I mean, why did they not install it like it is mentioned in the error message?

**Comment by mewio** [comment]
I don't know why they didn't want to depend on `magic`. Perhaps because its API has been somewhat unstable over the years, or because using its heuristics for guessing content type seems like a backwards approach when the content type is already known, or because they want to use in-memory images while libmagic was made for data stored in a filesystem, or simply to minimize their application's dependencies.

**Comment by odrling** [comment]
Well as long as it's a choice and not that something is broken when they use it I guess it's alright.

I will probably release a new version of peony some time this week, for now it should work fine with the code in the master branch.

**Comment by mewio** [comment]
Thanks!
