### ISSUE TITLE
statuses/filter.json example?

### ISSUE THREAD

**Issue by Rhodesia** [odrling/peony-twitter#12]
are there any examples or documentation on how to start up a publicstream with filters? I cant find anything about it anywhere

**Comment by odrling** [comment]
I don't think there is an example for this endpoint but it should be the same as with other endpoints, all the parameters are listed [in the Twitter documentation](https://dev.twitter.com/streaming/overview/request-parameters).

So it's something like:

    stream = client.stream.statuses.filter(track="hello")

And then it's just like any other stream.

**Comment by Rhodesia** [comment]
returning self.client.stream.statuses.filter.post(track="hello") for my event stream just hangs and doesn't emit the on_connect event

**Comment by odrling** [comment]
I don't think there is an `on_connect` event on this stream. `on_connect` is actually an alias for the `friends` event ([described here](https://dev.twitter.com/streaming/overview/messages-types#friends_list_friends)).

But I guess it would be better if this became an internal event (like `on_reconnect`) and so this would work on any stream.

**Comment by odrling** [comment]
Alright the `on_connect` event should work for any stream and has the same behaviour as the former event unless you need to access the "friends" list (You would have to use the `friends` event then)

**Comment by Rhodesia** [comment]
im guessing i would have to make a custom event for on_status right?

**Comment by odrling** [comment]
I'm not sure what you mean by this, this is just an attribute. Maybe you want the `on_tweet` event.

**Comment by Rhodesia** [comment]
on_tweet doesnt seem to pick up the tweets, I looked at the json being spit out by the default event and the first thing i saw was "created_at"

**Comment by odrling** [comment]
Hmm... Can you send one of them? I'd like to see what's going wrong.

**Comment by Rhodesia** [comment]
{'created_at': 'Fri Jun 30 12:28:29 +0000 2017', 'id': 880764978399236096, 'id_s                                                            tr': '880764978399236096', 'text': 'mais vale nem mandar porque tenho 90% que ia                                                            s ficar... — Tu é que sabes, mas eu não sou assim xD  https://t.co/tpNJEA1UeA',                                                             'source': '<a href="https://curiouscat.me" rel="nofollow">Curious Cat</a>', 'tru                                                            ncated': False, 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None                                                            , 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_scr                                                            een_name': None, 'user': {'id': 2790393852, 'id_str': '2790393852', 'name': 'Swe                                                            etheart', 'screen_name': 'alicefabx', 'location': 'made in útero', 'url': 'http:                                                            //notondrugz.tumblr.com/', 'description': '☯ team i don’t know what i’m doing wi                                                            th my life ☯ ✨A n t ó n i o✨A r r o i o✨ ☯purple babe', 'protected': False, 'ver                                                            ified': False, 'followers_count': 445, 'friends_count': 311, 'listed_count': 3,                                                             'favourites_count': 7156, 'statuses_count': 18090, 'created_at': 'Thu Sep 04 19:                                                            20:20 +0000 2014', 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, '                                                            lang': 'pt', 'contributors_enabled': False, 'is_translator': False, 'profile_bac                                                            kground_color': '000000', 'profile_background_image_url': 'http://pbs.twimg.com/                                                            profile_background_images/627138906677477376/aBKKjhna.jpg', 'profile_background_                                                            image_url_https': 'https://pbs.twimg.com/profile_background_images/6271389066774                                                            77376/aBKKjhna.jpg', 'profile_background_tile': True, 'profile_link_color': '000                                                            000', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '0                                                            00000', 'profile_text_color': '000000', 'profile_use_background_image': True, 'p                                                            rofile_image_url': 'http://pbs.twimg.com/profile_images/874994493078024192/uE-ZX                                                            SVC_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_image                                                            s/874994493078024192/uE-ZXSVC_normal.jpg', 'profile_banner_url': 'https://pbs.tw                                                            img.com/profile_banners/2790393852/1497715160', 'default_profile': False, 'defau                                                            lt_profile_image': False, 'following': None, 'follow_request_sent': None, 'notif                                                            ications': None}, 'geo': None, 'coordinates': None, 'place': None, 'contributors                                                            ': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'ent                                                            ities': {'hashtags': [], 'urls': [{'url': 'https://t.co/tpNJEA1UeA', 'expanded_u                                                            rl': 'https://curiouscat.me/alicefabx/post/171682384?t=1498825709', 'display_url                                                            ': 'curiouscat.me/alicefabx/post…', 'indices': [98, 121]}], 'user_mentions': [],                                                             'symbols': []}, 'favorited': False, 'retweeted': False, 'possibly_sensitive': F                                                            alse, 'filter_level': 'low', 'lang': 'pt', 'timestamp_ms': '1498825709329'}

**Comment by odrling** [comment]
I think this should work with on_tweet, which checks for a 'text' attribute in the data and for some reason checks that there is no 'event' attribute.
