### ISSUE TITLE
Streaming examples from the doc are not working

### ISSUE THREAD

**Issue by ewjoachim** [odrling/peony-twitter#14]
It seems that taking the "streaming" examples from the doc and using them as-is is producing the following error:
```python
async def track():
    req = client.stream.statuses.filter.post(track="uwu")
    async with req as ressource:
        print(req.text)  # print the tweet's text
```
```
Traceback (most recent call last):
  File "twitter_protocol_server.py", line 29, in <module>
    loop.run_until_complete(track())
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "twitter_protocol_server.py", line 26, in track
    print(req.text)  # print the tweet's text
AttributeError: 'StreamResponse' object has no attribute 'text'
```

https://peony-twitter.readthedocs.io/en/stable/usage/access.html#access-the-response-data-of-a-streaming-api-endpoint (and adding the missing `msg` before `.format`)(I could make another PR for that)
```
Traceback (most recent call last):
  File "twitter_protocol_server.py", line 41, in <module>
    loop.run_until_complete(track())
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "twitter_protocol_server.py", line 29, in track
    async for tweet in stream:
  File "/Users/mario/Envs/twitter-channel/lib/python3.6/site-packages/peony/stream.py", line 106, in __aiter__
    self.response = await self.connect()
  File "/Users/mario/Envs/twitter-channel/lib/python3.6/site-packages/peony/stream.py", line 86, in connect
    request = self.client.error_handler(self.session.request)
AttributeError: 'NoneType' object has no attribute 'request'
```

Some examples are working (like the `home()` and tweeting `I'm using Peony`), so I'm inclined to think my setup is good.

**Comment by odrling** [comment]
Hmm... The first `track` function doesn't make sense, not sure of what I had in mind when I wrote it. I'll remove this function in the first section (and add `msg` in the other).

**Comment by ewjoachim** [comment]
Hm, sorry that wasn't clear. The bug I have with the second function is **after** I add the missing `msg`. It's complaining about `self.session` being None, but still being used.

**Comment by ewjoachim** [comment]
Oh, BTW, sorry, I failed to mention something else I noticed : using `since_id=0` doesn't work. `since_id` should either be passed with a real value or not passed.

https://github.com/odrling/peony-twitter/blob/25493564dbda767ade307ec15185e9e4bc8c2a77/docs/usage/access.rst#how-to-access-the-api

**Comment by odrling** [comment]
Sorry I was so focused on the documentation that I missed the error in the traceback.
There is an error in the stream initialization that would not use the session that the client creates on the first connection.

Also it would the first "tweet" received would not actually be a stream but would be a connection notice (in case you'd want to do something when you connect to the stream). So the example will have to be updated as well.

**Comment by ewjoachim** [comment]
thank you ✨

**Comment by ewjoachim** [comment]
Oh, you even made a new release ! Perfect ! thank you a lot !
