### ISSUE TITLE
Please set a minimum aiohttp version

### ISSUE THREAD

**Issue by mattwwarren** [odrling/peony-twitter#15]
Hi there!

Thanks for this great library. I had been struggling with getting twython to do what I wanted for a while and this was a very easy replacement for a natively async, streaming library.

One piece of feedback from getting set up, however. I had to upgrade my version of aiohttp from 1.x to 3.x to fix `AttributeError: module 'aiohttp' has no attribute 'ClientPayloadError'`

I see that you require <4.0 but perhaps it should be >3.0,<4.0 since the ClientPayloadError was added in 3.0.

Thanks again! I'm happy to open a PR to this effect, unless there are concerns.

**Comment by odrling** [comment]
Thank you for contributing to this project.

Peony also works with aiohttp 2.x (`ClientPayloadError` was introduced in 2.0 if I remember well). One thing that changed with aiohttp 3.0 is that they dropped support for Python 3.5.2 and below which are still supported by my library.

So, I think it should be `>=2.0,<4.0`. You can open a PR, I'll include this change in a release soon.

**Comment by mattwwarren** [comment]
Oh, you're right. I didn't look closely enough. I think it was added in 2.3 (https://github.com/aio-libs/aiohttp/blob/v2.3.0/aiohttp/client_exceptions.py) Would that be okay to set as the minimum?

**Comment by odrling** [comment]
I ran the tests with aiohttp 2.0.0 and it worked. I don't think that would make sense to drop the versions <2.3 if they seem to work.

**Comment by odrling** [comment]
Well, it's done. I added an automated test in case aiohttp 2 would fail some time in the future.
