### ISSUE TITLE
Any proxy support for stream api?

### ISSUE THREAD

**Issue by Trim21** [odrling/peony-twitter#18]
python version: 3.6.1
peony-twitter: 1.1.0

args `proxy` says that `proxy : str     Proxy used with every request`. bug when i try `client.stream.statuses.filter`, the client direct connet to twitter insteam of connecting to proxy.

**Comment by odrling** [comment]
It seems that I forgot to check the proxy parameter when making the streaming requests. I think that would be a great occasion to change how this parameter works behind the scenes. That should not take very long.

**Comment by Trim21** [comment]
I have fixed it. Do you need a PR?

**Comment by odrling** [comment]
I'm not sure, I tried to remove the per request proxy parameter in favor of the client's proxy parameter. I don't really see someone using several proxies with a single client.

**Comment by odrling** [comment]
This should work as expected now. Maybe I'll create some tests to make sure that the proxy is really used but that would be another issue I guess.
