### ISSUE TITLE
Reusing an external ClientSession

### ISSUE THREAD

**Issue by fmarani** [odrling/peony-twitter#2]
I am writing a client that triggers many http requests simultaneously, one of which goes to Twitter to get the timeline. Unfortunately in this scenario the library triggers a RuntimeError, saying that the "Session is closed", probably because another coroutine cleaned this up before the twitter coroutine could trigger the http request.

Is it possible to pass in a ClientSession to the client object?

**Comment by odrling** [comment]
Until now the client created a session for every request (which is quite dumb I must admit), I'll push a new branch soon to add this.

**Comment by fmarani** [comment]
Tried the new branch and works. Thanks!
