### ISSUE TITLE
Crash with MemoryError on stream closed

### ISSUE THREAD

**Issue by spectras** [odrling/peony-twitter#24]
Hello,

Thanks for this nice lib! I have been using it for quite some time, but I noticed every now and then my service crashed. The issue is pretty elusive, but after many attemps I was able to pinpoint the conditions:
→ `StreamResponse` crashes if the remote server closes the connection unexpectedly.

It does not do so everytime, but I was able to interecept the service while the crash was in progress (memory use climbing several dozens MB pers second). I caught it in this loop consistently:
```python
            while not line:
                with async_timeout.timeout(90):
                    line = await self.response.content.readline()
                    line = line.strip(b'\r\n')
                    logger.debug("received data: %s" % line)
```
[Loop in context here](https://github.com/odrling/peony-twitter/blob/master/peony/stream.py#L155)

The issue is in case the connection is closed, aiohttp's [`readline`](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/streams.py) returns an empty `bytes` object, no exception raised. That behavior is [expected](https://docs.aiohttp.org/en/stable/streams.html#aiohttp.StreamReader.readline).

It causes infinite looping here, until the program exhausts all memory (`async_timeout` creates a `TimerHandle` at every iteration, the deletion of which is scheduled but not run as loop doesn't have the opportunity to do its job)

I don't know for sure how that situation arises in the first place. It *seems* to be a graceful disconnection initiated from twitter servers.

**Comment by odrling** [comment]
Thank you! I do remember running into this issue but I've never found out why it happened.

I'll change the library so that streams restart when they reach the EOF.
