### ISSUE TITLE
Using direct message

### ISSUE THREAD

**Issue by Luc1412** [odrling/peony-twitter#25]
I currently try to create a Twitter DM Chatbot with peony which reacts to Commands trough DMs.

I didn't find a way to send direct message/listen to them. 

Does the API support Direct Messages? 
If yes can a link to the documentation/example.
If not it would be a feature request.

**Comment by odrling** [comment]
You can send direct message with peony. It's not really an example but there is actually a test that sends a DM: https://github.com/odrling/peony-twitter/blob/967f98e16e1889389540f2e6acbf7cc7a1a80203/tests/test_twitter.py#L213-L237

Unlike all the other endpoints of the Twitter API (or at least those that I know of) the request is in json, so it uses `_json` parameter in the request.

You won't be able to get DMs in real time with peony now that twitter closed their userstream API. The only way to have it now would be to use the [Account Activity API](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview), I've never used it, but it's seems to send everything through a webhook, so it requires a publicly accessible server.

If you don't mind a bit of delay you can send a request per minute to this endpoint [GET direct_messages/events/list](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events) to get your DMs. But for a chatbot it would be weird.

A description of all the endpoints related to DMs is available in the twitter docs here: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/overview

**Comment by Luc1412** [comment]
Ok thx for your help
