### ISSUE TITLE
Error in exception error.

### ISSUE THREAD

**Issue by Painezor** [odrling/peony-twitter#3]
Task exception was never retrieved
Task exception was never retrieved
future: <Task finished coro=<Twitter.twat() done, defined at F:\Programs\My Shit\Discord bot\ext\toontweets.py:33> exception=TypeError("a bytes-like object is required, not 'str'",)>
Traceback (most recent call last):
  File "F:\Programs\My Shit\Discord bot\ext\toontweets.py", line 37, in twat
    async for tweet in stream:
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 90, in __aiter__
    raise await exceptions.throw(self.response)
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 31, in throw
    err = _get_error(data)
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 11, in _get_error
    if 'errors' in data:
TypeError: a bytes-like object is required, not 'str'

Trying to run a background task to stream tweets to discord for users, sometimes it works, sometimes it doesn't, but the traces aren't exactly being helpful, as apparently there's an error within the errors.

**Comment by odrling** [comment]
Can you show me the code that creates the stream? I'll try to create a branch where I catch this error to show what's in this data.

**Comment by odrling** [comment]
OK there is a [new branch](https://github.com/odrling/peony-twitter/tree/errorception) you can install it using pip: 
`pip3 install git+https://github.com/odrling/peony-twitter.git@errorception`

**Comment by odrling** [comment]
Nevermind it should not happen again, I'll update the package on pypi with these new changes

**Comment by Painezor** [comment]
Sorry, I was out of the house, but yeah. I can hastebin the module (it's for a discord bot, so it may look a bit odd).

Here's the module on hastebin https://hastebin.com/jidizucewi.py

**Comment by odrling** [comment]
Thanks, I was wondering if it was an error associated with the endpoint at first, but it doesn't seem like it. You can update peony from pypi now (the error should be gone).

It seems like there is an error when you connect/reconnect to the stream from the traceback and you should be able to see what this is about

**Comment by Painezor** [comment]
Yeah, apparently I'm providing a NoneType somehow... this confuses me. Using get_error on the coro is just providing me with 

```
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 88, in __aiter__
    self.response = await self.connect()
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 68, in connect
    request = self.client.error_handler(self.session.request)
AttributeError: 'NoneType' object has no attribute 'request'
```

Not sure why.

**Comment by odrling** [comment]
Hmm... There was something that was supposed to prevent the session from being None here but it seems like it failed here. I'll make an update that should make it sure that it is not None at this point. Now that's weird because I've never seen this error and it should already work fine.

**Comment by Painezor** [comment]
Getting the byteslike error again somehow.
```
Traceback for <Task finished coro=<Twitter.twat() done, defined at F:\Programs\My Shit\Discord bot\ext\toontweets.py:27> exception=TypeError("a bytes-like object is required, not 'str'",)> (most recent call last):
  File "F:\Programs\My Shit\Discord bot\ext\toontweets.py", line 97, in twat
    print("Escaped Async for tweet in stream somehow.")
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 125, in __anext__
    return await self.restart_stream(reconnect=0)
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 161, in restart_stream
    await self.__aiter__()
  File "F:\Programs\Python 3.6\lib\site-packages\peony\stream.py", line 95, in __aiter__
    return self
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 39, in throw
    raise exception(response=response, data=data, **kwargs)
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 58, in __init__
    message = self.get_message()
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 63, in get_message
    err = _get_error(self.data)
  File "F:\Programs\Python 3.6\lib\site-packages\peony\exceptions.py", line 11, in _get_error
    if 'errors' in data:
TypeError: a bytes-like object is required, not 'str
```
 used 
```
pip install peony-twitter --upgrade
Requirement already up-to-date: peony-twitter in f:\programs\python 3.6\lib\site-packages
Requirement already up-to-date: aiohttp in f:\programs\python 3.6\lib\site-packages (from peony-twitter)
Requirement already up-to-date: oauthlib in f:\programs\python 3.6\lib\site-packages (from peony-twitter)
Requirement already up-to-date: yarl<0.10,>=0.9.8 in f:\programs\python 3.6\lib\site-packages (from aiohttp->peon
er)
Requirement already up-to-date: multidict>=2.1.4 in f:\programs\python 3.6\lib\site-packages (from aiohttp->peony
r)
Requirement already up-to-date: async-timeout>=1.1.0 in f:\programs\python 3.6\lib\site-packages (from aiohttp->p
itter)
Requirement already up-to-date: chardet in f:\programs\python 3.6\lib\site-packages (from aiohttp->peony-twitter)
```
So I'm assuming that earlier fix might have got reverted somehow.  I'm pretty confused now.

**Comment by odrling** [comment]
OK so here you got an Enhance Your Calm Response from Twitter. 
Which means two things:
* I need to handle this error more properly (like here it produced another error again that's shameful). It should also let someone know if they're running into this error because it could mean that they are doing something inappropriate.
* You need to change your code, the endpoint you are using only supports [one connection by client disconnecting the first connection you've made](https://dev.twitter.com/streaming/public). So you were connecting again and again to the same endpoint until you get this Enhance Your Calm response. You can try to send the message to the right channel depending on the user that sent the tweet (or use 2 differently authenticated clients though it's a bit dirty).

I think we got to the end of this issue here. I'll update peony soon with the few changes I've mentioned.
