### ISSUE TITLE
Twitter `help/configuration` endpoint will be retired

### ISSUE THREAD

**Issue by pistatium** [odrling/peony-twitter#39]
There was an announcement that Twitter's `help/configuration` endpoint, which this library calls at startup, will be terminated at the end of May.

https://twitter.com/TwitterAPI/status/1394657341472088066

If this API is deprecated, can we still use the library without any problems?

**Comment by pistatium** [comment]
Thank you for your reply.
I am relieved to know that there is no problem.
I'll try the twitter_configuration option as well.

**Comment by odrling** [comment]
I forgot to reference this issue but the calls to this endpoint are removed in 8443c92841c22a467996c353404a5c6c356f7598.
I'm trying to get the tests to pass again with these changes before closing this issue.
