### ISSUE TITLE
Unclosed client session when calling get_oauth_token

### ISSUE THREAD

**Issue by alenpaul2001** [odrling/peony-twitter#40]
### Expected behavior

A graceful shutdown.

### Actual behavior
calling 
`get_oauth_token`

when trying to close
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb325b04ee0>
```
### version
python - 1.9.5
peony-twitter - latest
###

**Comment by odrling** [comment]
I think that should work fine with the latest commit.
Though I somehow don't get this message when calling these functions before this commit.

**Comment by alenpaul2001** [comment]
> I think that should work fine with the latest commit.
> Though I somehow don't get this message when calling these functions before this commit.
> EDIT: Oh thanks for testing then.

Thanks its working as expected.
