### ISSUE TITLE
'NoneType' object has no attribute 'request'

### ISSUE THREAD

**Issue by alenpaul2001** [odrling/peony-twitter#41]
code :

```
    async def verify_credentials(
        self, access_token: str, access_token_secret: str
    ) -> bool:
        client = PeonyClient(
            self.consumer_token,
            self.consumer_token_secret,
            access_token,
            access_token_secret,
        )
        try:
            await client._get_user()
            return True
        except NotAuthenticated:
            return False
        finally:
            await client.close()
```

Its working as expected, but it outputs weird exceptions:

```
[2021-05-30 16:26:23 +0530] [32959] [INFO] [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2756)
[2021-05-30 16:26:23 +0530] [32959] [ERROR] Task exception was never retrieved
future: <Task finished name='Task-43' coro=<ErrorHandler.__call__() done, defined at /home/user/.local/lib/python3.9/site-packages/peony/utils.py:94> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/peony/utils.py", line 100, in __call__
    return await self.__request(future=future, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/peony/client.py", line 338, in request
    async with session.request(**req_kwargs) as response:
AttributeError: 'NoneType' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/peony/utils.py", line 112, in __call__
    future.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
```
### versions
python - 1.9.5
peony-twitter - 2.0.0

**Comment by alenpaul2001** [comment]
I think I found the issue it is because of this particular task which is created during client initialization  https://github.com/odrling/peony-twitter/blob/88c7b6257d59962a97e34e496db78c7ca436dd9b/peony/client.py#L488

If the credentials are invalid this tasks fails. I fixed it by awaiting on client.user instead of spawing new client.._get_user() :

    async def verify_credentials(
        self, access_token: str, access_token_secret: str
    ) -> bool:
        client = PeonyClient(
            self.consumer_token,
            self.consumer_token_secret,
            access_token,
            access_token_secret,
        )
        try:
            await client.user
            return True
        except NotAuthenticated:
            return False
        finally:
            await client.close()

**Comment by odrling** [comment]
Yes, that should be what you use in an actual application (unless you expect your user information to change regularly, maybe someday I'll make it cache this response for some amount of time instead of keeping the same response forever).
That said that shows that if the client is closed quickly after being initialised the `client.user` task fails with this error, which comes from peony's aiohttp session getting closed before the task gets cancelled.
