### ISSUE TITLE
aiohttp 2.0?

### ISSUE THREAD

**Issue by Painezor** [odrling/peony-twitter#5]
Getting another error, I'm sure you love me by now. This is probably another enhance your calm, but, just in case it's not...

This one is happening after I updated to the latest version of aiohttp.

```Traceback for <Task finished coro=<Twitter.twat() done, defined at F:\Programs\DiscordVenv\Rewrite Bot\ext\toontweets.py:26> exception=AttributeError("module 'aiohttp' has no attribute 'errors'",)> (most recent call last):
  File "F:\Programs\DiscordVenv\Rewrite Bot\ext\toontweets.py", line 108, in twat
    print("Escaped async for tweet in stream somehow.")
  File "F:\programs\DiscordVenv\lib\site-packages\peony\stream.py", line 143, in __anext__
    except aiohttp.errors.ContentEncodingError:
AttributeError: module 'aiohttp' has no attribute 'errors'```

**Comment by odrling** [comment]
No it seems like a lot of things changed about exceptions in aiohttp 2.0

**Comment by odrling** [comment]
I think it should work now if you upgrade peony. Maybe I'll try to tune requirements.txt later to make sure nothing like this would happen in the future.

**Comment by odrling** [comment]
It seems I closed this issue to quickly, when using a newer version of aiohttp the stream would restart every 5 minutes. The latest release should not have this issue, sorry for that.
