### ISSUE TITLE
How would I go about getting an extended_tweet instead of tweet with the streaming api?

### ISSUE THREAD

**Issue by Painezor** [odrling/peony-twitter#6]
re this: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

I'm currently parsing the default versions of the tweets, which results in some tweets being truncated, is there a way to make it retrieve the extended_tweet instead?

**Comment by sabo** [comment]
Hi, just check the `truncated` attribute. If that's set, there should be an `extended_tweet` that has the full text.

**Comment by odrling** [comment]
Actually, should I deal with this from peony or just leave it as it is? I think that would be more natural to get the full text right from the text attribute.

**Comment by odrling** [comment]
Well, if you use the code on the master branch it should get the full text when you call the `text` attribute. That should not impact existing programs that already tried to get the full text.
