### ISSUE TITLE
breaking the loop?

### ISSUE THREAD

**Issue by Rhodesia** [odrling/peony-twitter#8]
how can i break off from the loop and go on to do other tasks?

**Comment by odrling** [comment]
If you mean that the loop keeps running forever after the task is completed you can do this:

    loop = asyncio.get_event_loop()
    client = YourClient(**creds, loop=loop)
    loop.run_until_complete(client.run_tasks())

The `run` method of PeonyClient currently assumes that the tasks will run forever, perhaps I should change it in the next release.

**Comment by Rhodesia** [comment]
AttributeError: 'Twitter' object has no attribute 'loop'

**Comment by Rhodesia** [comment]
heres my code:
```python
class Client(PeonyClient):
	pass
@Client.event_stream
class UserStream(EventStream):

	def stream_request(self):
		return userstream.user.get()
	@events.on_connect.handler
	def connection(self, data):
		print("Connected to stream!")

	# the on_tweet event is triggered when a tweet seems to be sent on
	# the stream, by default retweets are included
	@events.on_tweet.handler
	def tweet(self, data):
		print(data.text)
consumer_key = ""
consumer_secret = ""
access_token = ""
access_secret = ""
client = Client(consumer_key=consumer_key, consumer_secret=consumer_secret, access_token=access_token, access_token_secret=access_secret, loop=loop)
loop = asyncio.get_event_loop()
loop.run_until_complete(client.run_tasks())
```

**Comment by odrling** [comment]
That seems to work (if you use `self.userstream.user.get()` with self).
I don't know how you got the `AttributeError` too (if Twitter was a subclass of PeonyClient).

**Comment by odrling** [comment]
Little update on this issue: Clients now have a `close()` method that will stop the current tasks although it seems a bit hard to use.

For the error in the `EventStream` the biggest problem seems to be that no error was actually raised, so it looked like everything was normal but clearly it wasn't. That should be fixed in the latest release of peony.
